---
name: Build and verify image

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'docker-compose.yml'
      - '.gitignore'
      - '.github/linters*'
      - '.github/workflows/reusable-super-linter.yaml'
    branches:
      - 'main'
      - 'feature/*'
    tags:
      - '[0-9]+.[0-9]+-[0-9]+'
  pull_request:

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:

      # - name: Checkout
      #   uses: actions/checkout@v3

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          pull: true
          push: false
          load: true
          tags: meyay/languagetool:${{ github.run_id }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy for all CVEs
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: meyay/languagetool:${{ github.run_id }}
          exit-code: 0
          format: table

      - name: Run Trivy for HIGH,CRITICAL CVEs and report
        uses: aquasecurity/trivy-action@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          image-ref: meyay/languagetool:${{ github.run_id }}
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Test image
        run: |
          docker run --name=test --rm -p 127.0.0.1:8010:8010 --platform=linux/amd64 -d meyay/languagetool:${{ github.run_id }}
          sleep 10s
          docker logs test
          docker exec test /opt/java/customjre/bin/java --version
          docker exec test /entrypoint.sh help
          docker exec test /usr/local/bin/fasttext || true
          curl --data "language=en-US&text=a simple test" http://127.0.0.1:8010/v2/check | tee /dev/stderr | grep -q detectedLanguage
          docker stop test

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: meyay/languagetool
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Push to DockerHub
        uses: docker/build-push-action@v3
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          push: false
          platforms: linux/amd64
          cache-from: type=gha
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}